name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - website/**
  pull_request:
    branches:
      - master
    paths-ignore:
      - website/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          trust-check: false
          version: v0.2.7

      - name: Lint
        run: |
          selene generate-roblox-std
          selene src

      - name: Format
        run: stylua --check src

      - name: Install packages
        run: wally install

      - name: Build plugin
        run: rojo build -o IPS2DevKit.rbxm

      - uses: actions/upload-artifact@v3
        with:
          name: IPS2DevKit.rbxm
          path: IPS2DevKit.rbxm